//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PentagonHMI {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class FactoryRestore : global::System.Configuration.ApplicationSettingsBase {
        
        private static FactoryRestore defaultInstance = ((FactoryRestore)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new FactoryRestore())));
        
        public static FactoryRestore Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Singulation_Stepper_2DBarcode_Distance {
            get {
                return ((double)(this["Singulation_Stepper_2DBarcode_Distance"]));
            }
            set {
                this["Singulation_Stepper_2DBarcode_Distance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14.65")]
        public double Singulation_Stepper_Conveyor_Speed {
            get {
                return ((double)(this["Singulation_Stepper_Conveyor_Speed"]));
            }
            set {
                this["Singulation_Stepper_Conveyor_Speed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double FnB_Stepper_TicMark_Distance {
            get {
                return ((double)(this["FnB_Stepper_TicMark_Distance"]));
            }
            set {
                this["FnB_Stepper_TicMark_Distance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double UPC_Stepper_TicMark_Distance {
            get {
                return ((double)(this["UPC_Stepper_TicMark_Distance"]));
            }
            set {
                this["UPC_Stepper_TicMark_Distance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double UPC_Stepper_OQC_Distance {
            get {
                return ((double)(this["UPC_Stepper_OQC_Distance"]));
            }
            set {
                this["UPC_Stepper_OQC_Distance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5.5")]
        public double Sorting_Stepper_Sorter1_Transfer_Distance {
            get {
                return ((double)(this["Sorting_Stepper_Sorter1_Transfer_Distance"]));
            }
            set {
                this["Sorting_Stepper_Sorter1_Transfer_Distance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("191")]
        public double Sorting_Stepper_Sorter1_Reject_Distance {
            get {
                return ((double)(this["Sorting_Stepper_Sorter1_Reject_Distance"]));
            }
            set {
                this["Sorting_Stepper_Sorter1_Reject_Distance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public double Sorting_Stepper_Sorter1_Transfer_Speed {
            get {
                return ((double)(this["Sorting_Stepper_Sorter1_Transfer_Speed"]));
            }
            set {
                this["Sorting_Stepper_Sorter1_Transfer_Speed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public double Sorting_Stepper_Sorter1_Reject_Speed {
            get {
                return ((double)(this["Sorting_Stepper_Sorter1_Reject_Speed"]));
            }
            set {
                this["Sorting_Stepper_Sorter1_Reject_Speed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public double Sorting_Stepper_Sorter2_Transfer_Distance {
            get {
                return ((double)(this["Sorting_Stepper_Sorter2_Transfer_Distance"]));
            }
            set {
                this["Sorting_Stepper_Sorter2_Transfer_Distance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("193")]
        public double Sorting_Stepper_Sorter2_Reject_Distance {
            get {
                return ((double)(this["Sorting_Stepper_Sorter2_Reject_Distance"]));
            }
            set {
                this["Sorting_Stepper_Sorter2_Reject_Distance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public double Sorting_Stepper_Sorter2_Transfer_Speed {
            get {
                return ((double)(this["Sorting_Stepper_Sorter2_Transfer_Speed"]));
            }
            set {
                this["Sorting_Stepper_Sorter2_Transfer_Speed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public double Sorting_Stepper_Sorter2_Reject_Speed {
            get {
                return ((double)(this["Sorting_Stepper_Sorter2_Reject_Speed"]));
            }
            set {
                this["Sorting_Stepper_Sorter2_Reject_Speed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM5")]
        public string Singulation_Stepper_2DBarcode_COM {
            get {
                return ((string)(this["Singulation_Stepper_2DBarcode_COM"]));
            }
            set {
                this["Singulation_Stepper_2DBarcode_COM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM6")]
        public string Singulation_Stepper_Conveyor_COM {
            get {
                return ((string)(this["Singulation_Stepper_Conveyor_COM"]));
            }
            set {
                this["Singulation_Stepper_Conveyor_COM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM3")]
        public string FnB_Stepper_TicMark_COM {
            get {
                return ((string)(this["FnB_Stepper_TicMark_COM"]));
            }
            set {
                this["FnB_Stepper_TicMark_COM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM10")]
        public string UPC_Stepper_TicMark_COM {
            get {
                return ((string)(this["UPC_Stepper_TicMark_COM"]));
            }
            set {
                this["UPC_Stepper_TicMark_COM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM9")]
        public string UPC_Stepper_OQC_COM {
            get {
                return ((string)(this["UPC_Stepper_OQC_COM"]));
            }
            set {
                this["UPC_Stepper_OQC_COM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM11")]
        public string Sorting_Stepper_Sorter1_COM {
            get {
                return ((string)(this["Sorting_Stepper_Sorter1_COM"]));
            }
            set {
                this["Sorting_Stepper_Sorter1_COM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM13")]
        public string Sorting_Stepper_Sorter2_COM {
            get {
                return ((string)(this["Sorting_Stepper_Sorter2_COM"]));
            }
            set {
                this["Sorting_Stepper_Sorter2_COM"] = value;
            }
        }
    }
}
